# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/jammy64"

  # Timeout para boot
  config.vm.boot_timeout = 600  # 10 minutos

  # Forwarded ports
  config.vm.network "forwarded_port", guest: 81, host: 81
  config.vm.network "forwarded_port", guest: 80, host: 80
  config.vm.network "forwarded_port", guest: 3306, host: 3306
  config.vm.network "forwarded_port", guest: 8080, host: 8080
  config.vm.network "forwarded_port", guest: 9000, host: 9000
  config.vm.network "forwarded_port", guest: 19999, host: 19999
  config.vm.network "forwarded_port", guest: 9001, host: 9001

  # Private network
  config.vm.network "private_network", ip: "192.168.33.10"

  # Provider-specific configuration for VirtualBox
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "6144"
    vb.cpus = "8"
  end

  # Provisioning: install packages
  config.vm.provision "shell", inline: <<-SHELL
    sudo apt-get update && sudo apt-get install -y \
    swapspace \
    python-is-python3 \
    python3-pip \
    python3-dev \
    libmysqlclient-dev \
    python3-venv \
    build-essential \
    libssl-dev \
    libffi-dev \
    unzip \
    openjdk-17-jdk \
    mysql-server
  SHELL

  # MySQL setup
  $script_mysql = <<-SCRIPT
    # Configurar swap
    sudo fallocate -l 4G /swapfile
    sudo chmod 600 /swapfile
    sudo mkswap /swapfile
    sudo swapon /swapfile

    # Ajustar permissões e iniciar MySQL
    sudo chown -R mysql:mysql /var/lib/mysql
    sudo chmod -R 755 /var/lib/mysql

    # Criar os usuários
    sudo mysql -e "CREATE USER 'devops'@'%' IDENTIFIED BY 'mestre';"
    sudo mysql -e "CREATE USER 'devops_dev'@'%' IDENTIFIED BY 'mestre';"

    # Criar os bancos de dados
    sudo mysql -e "CREATE DATABASE todo;"
    sudo mysql -e "CREATE DATABASE todo_dev;"
    sudo mysql -e "CREATE DATABASE test_todo_dev;"

    # Conceder privilégios ao usuário 'devops' para todos os bancos de dados
    sudo mysql -e "GRANT ALL PRIVILEGES ON *.* TO 'devops'@'%' WITH GRANT OPTION;"

    # Conceder privilégios ao usuário 'devops_dev' apenas para os bancos de dados 'todo_dev' e 'test_todo_dev'
    sudo mysql -e "GRANT ALL PRIVILEGES ON todo_dev.* TO 'devops_dev'@'%';"
    sudo mysql -e "GRANT ALL PRIVILEGES ON test_todo_dev.* TO 'devops_dev'@'%';"

    # Atualizar privilégios
    sudo mysql -e "FLUSH PRIVILEGES;"
  SCRIPT

  config.vm.provision "shell", inline: $script_mysql

  # Ensure synced folders are ready before copying MySQL config
  config.vm.provision "shell", inline: <<-SHELL
    if [ -f /configs/mysqld.cnf ]; then
      sudo cp /configs/mysqld.cnf /etc/mysql/mysql.conf.d/mysqld.cnf
      sudo systemctl restart mysql
    else
      echo "mysqld.cnf not found, skipping copy."
    fi
    sudo systemctl restart ssh
  SHELL

  # SSH key insertion (optional: remove this line if you want Vagrant to manage SSH keys automatically)
  config.ssh.insert_key = false

  # Synced folders
  config.vm.synced_folder "./configs", "/configs"
  config.vm.synced_folder "./scripts", "/vagrant/scripts"

  # Execute custom scripts after setup
  config.vm.provision "shell", inline: <<-SHELL
    chmod +x /vagrant/scripts/*
    sudo /vagrant/scripts/docker.sh
    sudo usermod -aG docker $USER
    sudo usermod -aG docker jenkins
  SHELL

  # Remove the vagrant home directory (this is potentially unsafe, review this necessity)
  # config.vm.provision "shell", inline: "sudo rm -rf /home/vagrant/"
end
