# Generated by Django 2.1.7 on 2019-03-06 04:09

from django.db import migrations, models
from django.utils.timezone import now  # Importa timezone.now

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('text', models.TextField(blank=True)),
                ('created_at', models.DateField(blank=True, default=now)),  # Altere para timezone.now
                ('completed', models.BooleanField(default=False)),
            ],
        ),
    ]